name: Unzip project files

on:
  push:
    paths:
      - '*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install unzip

      - name: Unzip files
        run: unzip -o Supermarket-API-Project.zip -d ./

      - name: Add unzipped files to commit
        run: |
          git config --global user.name "tiago_tavares"
          git config --global user.email "tiago.tavares7390@gmail.com"
          git add .
          git commit -m "Unzipped project files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
